adding covid-19 form
avinashkranjan/lifeMEDeasy pull request #108
Opened 2021-04-07 18:02 UTC by kumarishalini6

I have made covid-19 patient section and test section in navbar. Kindly check it Thanks.

2021-04-08 19:52 UTC, chetan-rns commented
@kumarishalini6 Do we need `*.pyc` cache files in the PR? If we can ignore it, please add it to `.gitignore`.

2021-04-09 00:29 UTC, kumarishalini6 commented
@chetan-rns  Done now you ca proceed

2021-04-11 15:33 UTC, chetan-rns requested changes

2021-04-11 15:33 UTC, chetan-rns commented on src/components/CovidPatient.js
> +                                <input className="abc" type="number" placeholder="Enter your phone number"/>
Can we use a better class name instead of `abc`?

2021-04-11 15:33 UTC, chetan-rns commented on src/components/CovidPatient.js
> +                                    <option value="1">1.Fever</option>
How about storing the symptoms in an array and looping them to avoid repetition?

Something like:
```yaml
symptoms = ["Fever" , "Shortness of breath", ....]
for (symptom in symptoms) {
    <option value={index}>{symptom}</option>
}

```

2021-04-11 15:35 UTC, chetan-rns commented
also do we need `.gitignore2/__pycache__/__init__.cpython-38.pyc` files in the commit?

2021-04-11 15:38 UTC, kumarishalini6 commented
Ok I'll do that

2021-04-11 15:39 UTC, chetan-rns commented on src/components/CovidPatient.js
> +                                    <option value="1">1.Fever</option>
We have a lot of forms. We should make sure our components are being reused. Should check if we can use `react-form` package in the future

2021-04-11 17:30 UTC, kumarishalini6 commented
done @chetan-rns

2021-04-14 05:22 UTC, chetan-rns commented
@kumarishalini6 `.pyc` files still exists

![Screenshot from 2021-04-14 10-51-31](https://user-images.githubusercontent.com/21128732/114658474-794b9980-9d0f-11eb-92a5-8b921d1c2ada.png)


Please check the `Files changed` section in the PR

2021-04-15 08:38 UTC, chetan-rns requested changes

2021-04-15 08:38 UTC, chetan-rns commented on src/components/Darkmode.css
> +* {
@kumarishalini6 There are files related to Darkmode. Was this included intentionally? I see a different issue for this #112

2021-04-15 08:40 UTC, kumarishalini6 commented
It is different issue sorry

2021-04-15 08:43 UTC, kumarishalini6 commented
Is it ok or I have to resend the PR

2021-04-15 08:46 UTC, chetan-rns commented
@kumarishalini6 Separate PR for Darkmode would be better. Please avoid big PRs. We should introduce smaller and well-tested changes to the codebase.

2021-04-15 08:50 UTC, kumarishalini6 commented
Actually I was created it seperately it happens by mistake I'll remove it

2021-04-15 08:57 UTC, kumarishalini6 commented
now check it

2021-04-21 04:30 UTC, chetan-rns approved these changes

2021-05-14 05:53 UTC, merged