scroll
avinashkranjan/lifeMEDeasy pull request #148
Opened 2021-05-14 12:14 UTC by ChitvanRamani22

# Description

(Write your answer here.)

## Related Issues or Pull Requests

#145 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/avinashkranjan/Amazing-Python-Scripts/blob/master/CONTRIBUTING.md)?

- [y ] Yes
- [ ] No

### Checklist

- [ y] I've read the contribution guidelines.
- [ y] I've checked the issue list before deciding what to submit.
- [ y] I've edited the `README.md` and link to my code.

2021-05-15 07:30 UTC, chetan-rns commented
Thanks for the PR @ChitvanRamani22. Can you please update the commit message and add a description for the PR. Commit messages are helpful while debugging and should describe the change accurately.

2021-05-15 07:34 UTC, ChitvanRamani22 commented
@avinashkranjan done.

2021-05-15 07:38 UTC, chetan-rns requested changes

2021-05-15 07:38 UTC, chetan-rns commented on readme.md
> +
Why are we updating the README?

2021-05-15 07:39 UTC, chetan-rns commented
Please fix the merge conflict

2021-05-15 07:42 UTC, ChitvanRamani22 commented on readme.md
> +
I havent done that i automatically gets updated everytime.

2021-05-15 12:05 UTC, ChitvanRamani22 commented
@avinashkranjan i have resolved the merge conflicts.

2021-05-17 16:40 UTC, avinashkranjan commented
@ChitvanRamani22 Resolve the conflicts

2021-05-17 17:09 UTC, avinashkranjan commented
@ChitvanRamani22 Kindly change the colour of background of the arrow to colour theme of the project..

2021-05-17 17:10 UTC, ChitvanRamani22 commented
@avinashkranjan shall i change it to blue?

2021-05-17 17:14 UTC, avinashkranjan commented
> @avinashkranjan shall i change it to blue or black?

Use this color `#4a008f`

2021-05-17 17:20 UTC, ChitvanRamani22 commented
@avinashkranjan done!

2021-05-17 17:22 UTC, avinashkranjan approved these changes

2021-05-17 17:22 UTC, merged