improving buttons
avinashkranjan/lifeMEDeasy pull request #163
Opened 2021-05-21 16:21 UTC by kumarishalini6

#155 
I have improve style of every buttons in the forms.
![InkedReact App - Personal - Microsoft​ Edge 5_21_2021 09_45_27 PM_LI](https://user-images.githubusercontent.com/69043944/119168537-78dca780-ba0d-11eb-81ac-fd9fedbd24ad.jpg)

2021-05-23 15:50 UTC, chetan-rns requested changes

2021-05-23 15:50 UTC, chetan-rns commented on src/App.js
> -              path="/appointment"
Any specific reason why `appointment` is removed from the navbar?

2021-05-23 15:50 UTC, chetan-rns commented on src/components/PatientRegister.css
> +    /* margin-right: 10%; */
Can we remove these commented lines? Everything else looks good to me :+1:

2021-05-23 15:51 UTC, kumarishalini6 commented on src/components/PatientRegister.css
> +    /* margin-right: 10%; */
Just give me 5min

2021-05-23 15:56 UTC, kumarishalini6 commented
done

2021-05-23 16:05 UTC, kumarishalini6 commented on src/App.js
> -              path="/appointment"
because of that line the appointment buttons goes to the patient page. it was 2 times, that's why i have deleted the dummy one.

2021-05-23 16:05 UTC, chetan-rns commented on src/App.js
> -              path="/appointment"
@kumarishalini6  ^^

2021-05-23 16:06 UTC, chetan-rns commented on src/App.js
> -              path="/appointment"
:+1:

2021-05-23 16:09 UTC, chetan-rns commented
@kumarishalini6 Also please make sure to elaborate the commit messages in the future PRs. It would help others to understand the change introduced.

2021-05-23 16:09 UTC, chetan-rns approved these changes

2021-05-23 16:11 UTC, kumarishalini6 commented
Sure

2021-05-24 22:00 UTC, avinashkranjan approved these changes

2021-05-24 22:00 UTC, merged