improving navbar
avinashkranjan/lifeMEDeasy pull request #178
Opened 2021-05-26 17:17 UTC by kumarishalini6

#173 

There was so much stuff in the navbar I have removed  it and create a covid file from there links of patients and tests.
![lifeMEDeasy - Personal - Microsoft​ Edge 5_26_2021 10_35_11 PM](https://user-images.githubusercontent.com/69043944/119703618-31865a80-be03-11eb-86b6-1c2be3037df0.png)

2021-05-27 05:10 UTC, chetan-rns requested changes

2021-05-27 05:10 UTC, chetan-rns commented on src/components/NavbarItem.js
> +  <Container>
Is this commented file required?

2021-05-27 05:10 UTC, chetan-rns commented on src/components/NavbarItem.js
> +                                        <NavLink href="/emergency" className="links" ><span className="fa fa-info fa-lg"></span> Emergencies</NavLink>
Clicking on emergency is throwing an error. Could you please take a look?

2021-05-27 05:57 UTC, kumarishalini6 commented on src/components/NavbarItem.js
> +                                        <NavLink href="/emergency" className="links" ><span className="fa fa-info fa-lg"></span> Emergencies</NavLink>
ok let me check

2021-05-27 05:58 UTC, kumarishalini6 commented on src/components/NavbarItem.js
> +  <Container>
ok let me check

2021-05-27 06:02 UTC, kumarishalini6 commented on src/components/NavbarItem.js
> +  <Container>
sorry , no not required i was just checking something that's why

2021-05-27 06:06 UTC, kumarishalini6 commented on src/components/NavbarItem.js
> +                                        <NavLink href="/emergency" className="links" ><span className="fa fa-info fa-lg"></span> Emergencies</NavLink>
can you please show me the error

2021-05-27 06:07 UTC, kumarishalini6 commented on src/components/NavbarItem.js
> +                                        <NavLink href="/emergency" className="links" ><span className="fa fa-info fa-lg"></span> Emergencies</NavLink>
I have added className ="links" because of css

2021-06-03 17:53 UTC, avinashkranjan approved these changes
LGTM..💯

2021-06-03 17:53 UTC, merged